version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=275057777725
      - REGION=us-east-1
      - REPO_NAME=brain-tasks-app
      - IMAGE_URI=275057777725.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 275057777725.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t 275057777725.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 275057777725.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

      - echo "Writing Kubernetes manifests..."
      - sed -i "s|<IMAGE_URI>|275057777725.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest|" k8s/deployment.yaml
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - deployment.yaml
    - service.yaml

